version: '3.9'

services:
  frontend:
    build:
      context: .
    volumes:
      - ./nginx/api_redirection-local.conf:/opt/bitnami/nginx/conf/bitnami/api_redirection-local.conf:ro
    ports:
      - "8080:8080"
